spring.application.name=Task Manager

spring.jpa.open-in-view=false

spring.profiles.active=dev

spring.task.scheduling.cron=10 0 0 * * *
spring.user.scheduling.cron.every.day=20 0 1 * * *
spring.user.scheduling.cron.every.hour=0 0 */1 * * *
spring.refresh.token.scheduling.cron=20 0 2 * * *
spring.verification.token.scheduling.cron=20 0 3 * * *

jwt.token.secret=${JWT_TOKEN}
jwt.token.issuer=${JWT_ISSUER}
jwt.token.expiration=10

auth.password.pepper=${AUTH_PASSWORD_PEPPER}

cookie.secure=true

security.base.time.minutes=30
security.lock.max_attempts=5
security.refresh.token.expiration.days=12
security.refresh.token.grace.window.seconds=10

# Send mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=${MAILPIT_USER}
spring.mail.password=${MAILPIT_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*

spring.mail.email=taskmanager@mailpit.com