package com.vicente.taskmanager.controller.docs;

import com.vicente.taskmanager.exception.error.StandardError;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.core.io.Resource;
import org.springframework.http.ResponseEntity;

@Tag(
        name = "Local Signed File",
        description = "Endpoints for secure download of locally stored files. " +
                "Supports signed URLs with HMAC token, expiration, and custom Content-Disposition. " +
                "Includes security validation and access logging."
)
public interface LocalSignedFileControllerDoc {

    @Operation(
            summary = "Download file using signed URL",
            description = "Downloads a file stored locally using a signed URL. "
                    + "In Swagger UI, all parameters (`storageFileName`, `token`, `exp`, and `rscd`) must be filled manually, "
                    + "as they are generated by the 'Generate Signed URL' endpoint."
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "200",
                    description = "File downloaded successfully",
                    content = @Content(mediaType = "application/octet-stream")
            ),
            @ApiResponse(
                    responseCode = "403",
                    description = "Invalid token or signed URL expired",
                    content = @Content  // <-- sem schema, diz que não tem corpo
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "File not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = StandardError.class)
                    )
            ),
            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error. " +
                            "Could be due to HMAC token generation (no response body) " +
                            "or file download failure (returns JSON with error details)",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = StandardError.class)
                    )
            )
    })
    ResponseEntity<Resource> downloadSigned(
            @Parameter(description = "Stored file name", required = true, in = ParameterIn.PATH)
            String storageFileName,
            @Parameter(description = "Expiration timestamp of the URL (epoch seconds)", required = true, in = ParameterIn.QUERY)
            Long expireAt,
            @Parameter(description = "HMAC token for URL validation", required = true, in = ParameterIn.QUERY)
            String token,
            @Parameter(description = "Content-Disposition header for the downloaded file", required = true, in = ParameterIn.QUERY)
            String contentDisposition
    );
}
