CREATE TYPE account_status AS ENUM ('PENDING_VERIFICATION', 'DISABLED_BY_ADMIN', 'ACTIVE');

ALTER TABLE tb_user
ADD COLUMN account_status account_status NOT NULL DEFAULT 'PENDING_VERIFICATION',
DROP COLUMN is_enabled;